import { getPackagesTable } from "@/supabase/server/packages";
import { PackagesTable } from "./PackagesTable";
import { TablesPageClient } from "../TablesPageClient";
import type { TableStat } from "../TablesHeaderStats";
import { getAggregatePackages } from "@/backend/data/PackageStats";

export default async function PackagesMasterTablePage() {
    const packages = await getPackagesTable();
    const stats_data = getAggregatePackages(packages);

    const stats: TableStat[] = [
        { type: "package", value: stats_data.packageCount, desc: "Total school packages" },
        { type: "bookings", value: stats_data.totalBookings, label: "Bookings", desc: "Total confirmed bookings" },
        { type: "requests", value: stats_data.totalRequests, label: "Requests", desc: "Incoming package requests" },
        { type: "revenue", value: stats_data.totalRevenue.toFixed(0), desc: "Total revenue generated by confirmed bookings" }
    ];

    return (
        <TablesPageClient
            title="Packages Master Table"
            description="Manage school packages, lesson pricing, and student capacity."
            stats={stats}
        >
            <PackagesTable packages={packages} />
        </TablesPageClient>
    );
}