import { getPackagesTable } from "@/supabase/server/packages";
import { PackagesTable } from "./PackagesTable";
import { TableLayout } from "../TableLayout";
import type { TableStat } from "../TablesHeaderStats";
import { getAggregatePackages } from "@/backend/data/PackageStats";

export const dynamic = "force-dynamic";

export default async function PackagesMasterTablePage() {
    const packages = await getPackagesTable();
    const stats_data = getAggregatePackages(packages);

    const stats: TableStat[] = [
        { type: "package", value: stats_data.packageCount, desc: "Total school packages" },
        { type: "bookings", value: stats_data.totalBookings, label: "Bookings", desc: "Total confirmed bookings" },
        { type: "requests", value: stats_data.totalRequests, label: "Requests", desc: "Incoming package requests" },
        { type: "revenue", value: stats_data.totalRevenue, desc: "Total revenue generated by confirmed bookings" },
    ];

    return (
        <TableLayout stats={stats}>
            <PackagesTable packages={packages} showActions={true} />
        </TableLayout>
    );
}
