import type { TimelineEvent } from "@/src/components/timeline/types";

export interface TransactionEventFinancials {
    teacherEarnings: number;
    studentRevenue: number;
    profit: number;
    currency: string;
    commissionType: "fixed" | "percentage";
    commissionValue: number;
}

export interface TransactionEventPackage {
    description: string;
    pricePerStudent: number;
    durationMinutes: number;
    categoryEquipment: string;
    capacityEquipment: number;
    capacityStudents: number;
}

export interface TransactionEventEquipment {
    id: string;
    brand: string;
    model: string;
    size: number | null;
    sku?: string;
    color?: string;
}

export interface TransactionEventCommission {
    id: string;
    type: "fixed" | "percentage";
    cph: number;
    description: string | null;
}

export interface TransactionEventStudent {
    id: string;
    firstName: string;
    lastName: string;
    passport?: string;
    country?: string;
    phone?: string;
}

/**
 * Single source of truth for an Event and its context.
 * Structured to mirror the DB schema hierarchy.
 */
export interface TransactionEventData {
    // The Event itself
    event: {
        id: string;
        lessonId: string;
        date: string;
        duration: number;
        location: string | null;
        status: string;
    };

    // The Lesson context
    lesson: {
        id: string;
        status: string;
    };

    // The Booking context
    booking: {
        id: string;
        leaderStudentName: string;
        status: string;
        students: TransactionEventStudent[];
    };

    // Other relations & computed data
    teacher: {
        id?: string;
        username: string;
    };
    packageData: TransactionEventPackage;
    commission: TransactionEventCommission;
    financials: TransactionEventFinancials;
    equipments?: TransactionEventEquipment[];
}

/**
 * Derived Group: Represents a summary of all events within a single Lesson.
 * Generated by grouping TransactionEventData[] by lessonId.
 */
export interface LessonRow {
    lessonId: string;
    bookingId: string;
    leaderName: string;
    dateStart: string;
    dateEnd: string;
    lessonStatus: string;
    bookingStatus: string;
    commissionType: string;
    cph: number;
    commissionDescription: string | null;
    totalDuration: number;
    totalHours: number;
    totalEarning: number;
    totalRevenue: number;
    totalPayments: number;
    eventCount: number;
    events: TimelineEvent[];
    equipmentCategory: string;
    studentCapacity: number;
}