export interface Country {
  code: string;
  name: string;
  label: string;
  phoneCode: string;
}

export const COUNTRIES: Country[] = [
    { code: "AF", name: "Afghanistan", label: "Afghanistan", phoneCode: "+93" },
    { code: "AD", name: "Andorra", label: "Andorra", phoneCode: "+376" },
    { code: "AE", name: "United Arab Emirates", label: "United Arab Emirates", phoneCode: "+971" },
    { code: "AG", name: "Antigua and Barbuda", label: "Antigua and Barbuda", phoneCode: "+1" },
    { code: "AI", name: "Anguilla", label: "Anguilla", phoneCode: "+1" },
    { code: "AL", name: "Albania", label: "Albania", phoneCode: "+355" },
    { code: "AM", name: "Armenia", label: "Armenia", phoneCode: "+374" },
    { code: "AO", name: "Angola", label: "Angola", phoneCode: "+244" },
    { code: "AQ", name: "Antarctica", label: "Antarctica", phoneCode: "+672" },
    { code: "AR", name: "Argentina", label: "Argentina", phoneCode: "+54" },
    { code: "AS", name: "American Samoa", label: "American Samoa", phoneCode: "+1" },
    { code: "AT", name: "Austria", label: "Austria", phoneCode: "+43" },
    { code: "AU", name: "Australia", label: "Australia", phoneCode: "+61" },
    { code: "AW", name: "Aruba", label: "Aruba", phoneCode: "+297" },
    { code: "AX", name: "Åland Islands", label: "Åland Islands", phoneCode: "+358" },
    { code: "AZ", name: "Azerbaijan", label: "Azerbaijan", phoneCode: "+994" },
    { code: "BA", name: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", phoneCode: "+387" },
    { code: "BB", name: "Barbados", label: "Barbados", phoneCode: "+1" },
    { code: "BD", name: "Bangladesh", label: "Bangladesh", phoneCode: "+880" },
    { code: "BE", name: "Belgium", label: "Belgium", phoneCode: "+32" },
    { code: "BF", name: "Burkina Faso", label: "Burkina Faso", phoneCode: "+226" },
    { code: "BG", name: "Bulgaria", label: "Bulgaria", phoneCode: "+359" },
    { code: "BH", name: "Bahrain", label: "Bahrain", phoneCode: "+973" },
    { code: "BI", name: "Burundi", label: "Burundi", phoneCode: "+257" },
    { code: "BJ", name: "Benin", label: "Benin", phoneCode: "+229" },
    { code: "BL", name: "Saint Barthélemy", label: "Saint Barthélemy", phoneCode: "+590" },
    { code: "BM", name: "Bermuda", label: "Bermuda", phoneCode: "+1" },
    { code: "BN", name: "Brunei", label: "Brunei", phoneCode: "+673" },
    { code: "BO", name: "Bolivia", label: "Bolivia", phoneCode: "+591" },
    { code: "BQ", name: "Caribbean Netherlands", label: "Caribbean Netherlands", phoneCode: "+599" },
    { code: "BR", name: "Brazil", label: "Brazil", phoneCode: "+55" },
    { code: "BS", name: "Bahamas", label: "Bahamas", phoneCode: "+1" },
    { code: "BT", name: "Bhutan", label: "Bhutan", phoneCode: "+975" },
    { code: "BV", name: "Bouvet Island", label: "Bouvet Island", phoneCode: "+47" },
    { code: "BW", name: "Botswana", label: "Botswana", phoneCode: "+267" },
    { code: "BY", name: "Belarus", label: "Belarus", phoneCode: "+375" },
    { code: "BZ", name: "Belize", label: "Belize", phoneCode: "+501" },
    { code: "CA", name: "Canada", label: "Canada", phoneCode: "+1" },
    { code: "CC", name: "Cocos Islands", label: "Cocos (Keeling) Islands", phoneCode: "+61" },
    { code: "CD", name: "Democratic Republic of the Congo", label: "Congo (DRC)", phoneCode: "+243" },
    { code: "CF", name: "Central African Republic", label: "Central African Republic", phoneCode: "+236" },
    { code: "CG", name: "Republic of the Congo", label: "Congo (Republic)", phoneCode: "+242" },
    { code: "CH", name: "Switzerland", label: "Switzerland", phoneCode: "+41" },
    { code: "CI", name: "Côte d'Ivoire", label: "Côte d'Ivoire", phoneCode: "+225" },
    { code: "CK", name: "Cook Islands", label: "Cook Islands", phoneCode: "+682" },
    { code: "CL", name: "Chile", label: "Chile", phoneCode: "+56" },
    { code: "CM", name: "Cameroon", label: "Cameroon", phoneCode: "+237" },
    { code: "CN", name: "China", label: "China", phoneCode: "+86" },
    { code: "CO", name: "Colombia", label: "Colombia", phoneCode: "+57" },
    { code: "CR", name: "Costa Rica", label: "Costa Rica", phoneCode: "+506" },
    { code: "CU", name: "Cuba", label: "Cuba", phoneCode: "+53" },
    { code: "CV", name: "Cape Verde", label: "Cape Verde", phoneCode: "+238" },
    { code: "CW", name: "Curaçao", label: "Curaçao", phoneCode: "+599" },
    { code: "CX", name: "Christmas Island", label: "Christmas Island", phoneCode: "+61" },
    { code: "CY", name: "Cyprus", label: "Cyprus", phoneCode: "+357" },
    { code: "CZ", name: "Czech Republic", label: "Czech Republic", phoneCode: "+420" },
    { code: "DE", name: "Germany", label: "Germany", phoneCode: "+49" },
    { code: "DJ", name: "Djibouti", label: "Djibouti", phoneCode: "+253" },
    { code: "DK", name: "Denmark", label: "Denmark", phoneCode: "+45" },
    { code: "DM", name: "Dominica", label: "Dominica", phoneCode: "+1" },
    { code: "DO", name: "Dominican Republic", label: "Dominican Republic", phoneCode: "+1" },
    { code: "DZ", name: "Algeria", label: "Algeria", phoneCode: "+213" },
    { code: "EC", name: "Ecuador", label: "Ecuador", phoneCode: "+593" },
    { code: "EE", name: "Estonia", label: "Estonia", phoneCode: "+372" },
    { code: "EG", name: "Egypt", label: "Egypt", phoneCode: "+20" },
    { code: "EH", name: "Western Sahara", label: "Western Sahara", phoneCode: "+212" },
    { code: "ER", name: "Eritrea", label: "Eritrea", phoneCode: "+291" },
    { code: "ES", name: "Spain", label: "Spain", phoneCode: "+34" },
    { code: "ET", name: "Ethiopia", label: "Ethiopia", phoneCode: "+251" },
    { code: "FI", name: "Finland", label: "Finland", phoneCode: "+358" },
    { code: "FJ", name: "Fiji", label: "Fiji", phoneCode: "+679" },
    { code: "FK", name: "Falkland Islands", label: "Falkland Islands", phoneCode: "+500" },
    { code: "FM", name: "Micronesia", label: "Micronesia", phoneCode: "+691" },
    { code: "FO", name: "Faroe Islands", label: "Faroe Islands", phoneCode: "+298" },
    { code: "FR", name: "France", label: "France", phoneCode: "+33" },
    { code: "GA", name: "Gabon", label: "Gabon", phoneCode: "+241" },
    { code: "GB", name: "United Kingdom", label: "United Kingdom", phoneCode: "+44" },
    { code: "GD", name: "Grenada", label: "Grenada", phoneCode: "+1" },
    { code: "GE", name: "Georgia", label: "Georgia", phoneCode: "+995" },
    { code: "GF", name: "French Guiana", label: "French Guiana", phoneCode: "+594" },
    { code: "GG", name: "Guernsey", label: "Guernsey", phoneCode: "+44" },
    { code: "GH", name: "Ghana", label: "Ghana", phoneCode: "+233" },
    { code: "GI", name: "Gibraltar", label: "Gibraltar", phoneCode: "+350" },
    { code: "GL", name: "Greenland", label: "Greenland", phoneCode: "+299" },
    { code: "GM", name: "Gambia", label: "Gambia", phoneCode: "+220" },
    { code: "GN", name: "Guinea", label: "Guinea", phoneCode: "+224" },
    { code: "GP", name: "Guadeloupe", label: "Guadeloupe", phoneCode: "+590" },
    { code: "GQ", name: "Equatorial Guinea", label: "Equatorial Guinea", phoneCode: "+240" },
    { code: "GR", name: "Greece", label: "Greece", phoneCode: "+30" },
    { code: "GS", name: "South Georgia", label: "South Georgia", phoneCode: "+500" },
    { code: "GT", name: "Guatemala", label: "Guatemala", phoneCode: "+502" },
    { code: "GU", name: "Guam", label: "Guam", phoneCode: "+1" },
    { code: "GW", name: "Guinea-Bissau", label: "Guinea-Bissau", phoneCode: "+245" },
    { code: "GY", name: "Guyana", label: "Guyana", phoneCode: "+592" },
    { code: "HK", name: "Hong Kong", label: "Hong Kong", phoneCode: "+852" },
    { code: "HM", name: "Heard Island", label: "Heard Island", phoneCode: "+672" },
    { code: "HN", name: "Honduras", label: "Honduras", phoneCode: "+504" },
    { code: "HR", name: "Croatia", label: "Croatia", phoneCode: "+385" },
    { code: "HT", name: "Haiti", label: "Haiti", phoneCode: "+509" },
    { code: "HU", name: "Hungary", label: "Hungary", phoneCode: "+36" },
    { code: "ID", name: "Indonesia", label: "Indonesia", phoneCode: "+62" },
    { code: "IE", name: "Ireland", label: "Ireland", phoneCode: "+353" },
    { code: "IL", name: "Israel", label: "Israel", phoneCode: "+972" },
    { code: "IM", name: "Isle of Man", label: "Isle of Man", phoneCode: "+44" },
    { code: "IN", name: "India", label: "India", phoneCode: "+91" },
    { code: "IO", name: "British Indian Ocean Territory", label: "British Indian Ocean Territory", phoneCode: "+246" },
    { code: "IQ", name: "Iraq", label: "Iraq", phoneCode: "+964" },
    { code: "IR", name: "Iran", label: "Iran", phoneCode: "+98" },
    { code: "IS", name: "Iceland", label: "Iceland", phoneCode: "+354" },
    { code: "IT", name: "Italy", label: "Italy", phoneCode: "+39" },
    { code: "JE", name: "Jersey", label: "Jersey", phoneCode: "+44" },
    { code: "JM", name: "Jamaica", label: "Jamaica", phoneCode: "+1" },
    { code: "JO", name: "Jordan", label: "Jordan", phoneCode: "+962" },
    { code: "JP", name: "Japan", label: "Japan", phoneCode: "+81" },
    { code: "KE", name: "Kenya", label: "Kenya", phoneCode: "+254" },
    { code: "KG", name: "Kyrgyzstan", label: "Kyrgyzstan", phoneCode: "+996" },
    { code: "KH", name: "Cambodia", label: "Cambodia", phoneCode: "+855" },
    { code: "KI", name: "Kiribati", label: "Kiribati", phoneCode: "+686" },
    { code: "KM", name: "Comoros", label: "Comoros", phoneCode: "+269" },
    { code: "KN", name: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis", phoneCode: "+1" },
    { code: "KP", name: "North Korea", label: "North Korea", phoneCode: "+850" },
    { code: "KR", name: "South Korea", label: "South Korea", phoneCode: "+82" },
    { code: "KW", name: "Kuwait", label: "Kuwait", phoneCode: "+965" },
    { code: "KY", name: "Cayman Islands", label: "Cayman Islands", phoneCode: "+1" },
    { code: "KZ", name: "Kazakhstan", label: "Kazakhstan", phoneCode: "+7" },
    { code: "LA", name: "Laos", label: "Laos", phoneCode: "+856" },
    { code: "LB", name: "Lebanon", label: "Lebanon", phoneCode: "+961" },
    { code: "LC", name: "Saint Lucia", label: "Saint Lucia", phoneCode: "+1" },
    { code: "LI", name: "Liechtenstein", label: "Liechtenstein", phoneCode: "+423" },
    { code: "LK", name: "Sri Lanka", label: "Sri Lanka", phoneCode: "+94" },
    { code: "LR", name: "Liberia", label: "Liberia", phoneCode: "+231" },
    { code: "LS", name: "Lesotho", label: "Lesotho", phoneCode: "+266" },
    { code: "LT", name: "Lithuania", label: "Lithuania", phoneCode: "+370" },
    { code: "LU", name: "Luxembourg", label: "Luxembourg", phoneCode: "+352" },
    { code: "LV", name: "Latvia", label: "Latvia", phoneCode: "+371" },
    { code: "LY", name: "Libya", label: "Libya", phoneCode: "+218" },
    { code: "MA", name: "Morocco", label: "Morocco", phoneCode: "+212" },
    { code: "MC", name: "Monaco", label: "Monaco", phoneCode: "+377" },
    { code: "MD", name: "Moldova", label: "Moldova", phoneCode: "+373" },
    { code: "ME", name: "Montenegro", label: "Montenegro", phoneCode: "+382" },
    { code: "MF", name: "Saint Martin", label: "Saint Martin", phoneCode: "+590" },
    { code: "MG", name: "Madagascar", label: "Madagascar", phoneCode: "+261" },
    { code: "MH", name: "Marshall Islands", label: "Marshall Islands", phoneCode: "+692" },
    { code: "MK", name: "North Macedonia", label: "North Macedonia", phoneCode: "+389" },
    { code: "ML", name: "Mali", label: "Mali", phoneCode: "+223" },
    { code: "MM", name: "Myanmar", label: "Myanmar", phoneCode: "+95" },
    { code: "MN", name: "Mongolia", label: "Mongolia", phoneCode: "+976" },
    { code: "MO", name: "Macao", label: "Macao", phoneCode: "+853" },
    { code: "MP", name: "Northern Mariana Islands", label: "Northern Mariana Islands", phoneCode: "+1" },
    { code: "MQ", name: "Martinique", label: "Martinique", phoneCode: "+596" },
    { code: "MR", name: "Mauritania", label: "Mauritania", phoneCode: "+222" },
    { code: "MS", name: "Montserrat", label: "Montserrat", phoneCode: "+1" },
    { code: "MT", name: "Malta", label: "Malta", phoneCode: "+356" },
    { code: "MU", name: "Mauritius", label: "Mauritius", phoneCode: "+230" },
    { code: "MV", name: "Maldives", label: "Maldives", phoneCode: "+960" },
    { code: "MW", name: "Malawi", label: "Malawi", phoneCode: "+265" },
    { code: "MX", name: "Mexico", label: "Mexico", phoneCode: "+52" },
    { code: "MY", name: "Malaysia", label: "Malaysia", phoneCode: "+60" },
    { code: "MZ", name: "Mozambique", label: "Mozambique", phoneCode: "+258" },
    { code: "NA", name: "Namibia", label: "Namibia", phoneCode: "+264" },
    { code: "NC", name: "New Caledonia", label: "New Caledonia", phoneCode: "+687" },
    { code: "NE", name: "Niger", label: "Niger", phoneCode: "+227" },
    { code: "NF", name: "Norfolk Island", label: "Norfolk Island", phoneCode: "+672" },
    { code: "NG", name: "Nigeria", label: "Nigeria", phoneCode: "+234" },
    { code: "NI", name: "Nicaragua", label: "Nicaragua", phoneCode: "+505" },
    { code: "NL", name: "Netherlands", label: "Netherlands", phoneCode: "+31" },
    { code: "NO", name: "Norway", label: "Norway", phoneCode: "+47" },
    { code: "NP", name: "Nepal", label: "Nepal", phoneCode: "+977" },
    { code: "NR", name: "Nauru", label: "Nauru", phoneCode: "+674" },
    { code: "NU", name: "Niue", label: "Niue", phoneCode: "+683" },
    { code: "NZ", name: "New Zealand", label: "New Zealand", phoneCode: "+64" },
    { code: "OM", name: "Oman", label: "Oman", phoneCode: "+968" },
    { code: "PA", name: "Panama", label: "Panama", phoneCode: "+507" },
    { code: "PE", name: "Peru", label: "Peru", phoneCode: "+51" },
    { code: "PF", name: "French Polynesia", label: "French Polynesia", phoneCode: "+689" },
    { code: "PG", name: "Papua New Guinea", label: "Papua New Guinea", phoneCode: "+675" },
    { code: "PH", name: "Philippines", label: "Philippines", phoneCode: "+63" },
    { code: "PK", name: "Pakistan", label: "Pakistan", phoneCode: "+92" },
    { code: "PL", name: "Poland", label: "Poland", phoneCode: "+48" },
    { code: "PM", name: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon", phoneCode: "+508" },
    { code: "PN", name: "Pitcairn", label: "Pitcairn", phoneCode: "+870" },
    { code: "PR", name: "Puerto Rico", label: "Puerto Rico", phoneCode: "+1" },
    { code: "PS", name: "Palestine", label: "Palestine", phoneCode: "+970" },
    { code: "PT", name: "Portugal", label: "Portugal", phoneCode: "+351" },
    { code: "PW", name: "Palau", label: "Palau", phoneCode: "+680" },
    { code: "PY", name: "Paraguay", label: "Paraguay", phoneCode: "+595" },
    { code: "QA", name: "Qatar", label: "Qatar", phoneCode: "+974" },
    { code: "RE", name: "Réunion", label: "Réunion", phoneCode: "+262" },
    { code: "RO", name: "Romania", label: "Romania", phoneCode: "+40" },
    { code: "RS", name: "Serbia", label: "Serbia", phoneCode: "+381" },
    { code: "RU", name: "Russia", label: "Russia", phoneCode: "+7" },
    { code: "RW", name: "Rwanda", label: "Rwanda", phoneCode: "+250" },
    { code: "SA", name: "Saudi Arabia", label: "Saudi Arabia", phoneCode: "+966" },
    { code: "SB", name: "Solomon Islands", label: "Solomon Islands", phoneCode: "+677" },
    { code: "SC", name: "Seychelles", label: "Seychelles", phoneCode: "+248" },
    { code: "SD", name: "Sudan", label: "Sudan", phoneCode: "+249" },
    { code: "SE", name: "Sweden", label: "Sweden", phoneCode: "+46" },
    { code: "SG", name: "Singapore", label: "Singapore", phoneCode: "+65" },
    { code: "SH", name: "Saint Helena", label: "Saint Helena", phoneCode: "+290" },
    { code: "SI", name: "Slovenia", label: "Slovenia", phoneCode: "+386" },
    { code: "SJ", name: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen", phoneCode: "+47" },
    { code: "SK", name: "Slovakia", label: "Slovakia", phoneCode: "+421" },
    { code: "SL", name: "Sierra Leone", label: "Sierra Leone", phoneCode: "+232" },
    { code: "SM", name: "San Marino", label: "San Marino", phoneCode: "+378" },
    { code: "SN", name: "Senegal", label: "Senegal", phoneCode: "+221" },
    { code: "SO", name: "Somalia", label: "Somalia", phoneCode: "+252" },
    { code: "SR", name: "Suriname", label: "Suriname", phoneCode: "+597" },
    { code: "SS", name: "South Sudan", label: "South Sudan", phoneCode: "+211" },
    { code: "ST", name: "São Tomé and Príncipe", label: "São Tomé and Príncipe", phoneCode: "+239" },
    { code: "SV", name: "El Salvador", label: "El Salvador", phoneCode: "+503" },
    { code: "SX", name: "Sint Maarten", label: "Sint Maarten", phoneCode: "+1" },
    { code: "SY", name: "Syria", label: "Syria", phoneCode: "+963" },
    { code: "SZ", name: "Eswatini", label: "Eswatini", phoneCode: "+268" },
    { code: "TC", name: "Turks and Caicos Islands", label: "Turks and Caicos Islands", phoneCode: "+1" },
    { code: "TD", name: "Chad", label: "Chad", phoneCode: "+235" },
    { code: "TF", name: "French Southern Territories", label: "French Southern Territories", phoneCode: "+262" },
    { code: "TG", name: "Togo", label: "Togo", phoneCode: "+228" },
    { code: "TH", name: "Thailand", label: "Thailand", phoneCode: "+66" },
    { code: "TJ", name: "Tajikistan", label: "Tajikistan", phoneCode: "+992" },
    { code: "TK", name: "Tokelau", label: "Tokelau", phoneCode: "+690" },
    { code: "TL", name: "Timor-Leste", label: "Timor-Leste", phoneCode: "+670" },
    { code: "TM", name: "Turkmenistan", label: "Turkmenistan", phoneCode: "+993" },
    { code: "TN", name: "Tunisia", label: "Tunisia", phoneCode: "+216" },
    { code: "TO", name: "Tonga", label: "Tonga", phoneCode: "+676" },
    { code: "TR", name: "Turkey", label: "Turkey", phoneCode: "+90" },
    { code: "TT", name: "Trinidad and Tobago", label: "Trinidad and Tobago", phoneCode: "+1" },
    { code: "TV", name: "Tuvalu", label: "Tuvalu", phoneCode: "+688" },
    { code: "TW", name: "Taiwan", label: "Taiwan", phoneCode: "+886" },
    { code: "TZ", name: "Tanzania", label: "Tanzania", phoneCode: "+255" },
    { code: "UA", name: "Ukraine", label: "Ukraine", phoneCode: "+380" },
    { code: "UG", name: "Uganda", label: "Uganda", phoneCode: "+256" },
    { code: "UM", name: "United States Minor Outlying Islands", label: "US Minor Outlying Islands", phoneCode: "+1" },
    { code: "US", name: "United States", label: "United States", phoneCode: "+1" },
    { code: "UY", name: "Uruguay", label: "Uruguay", phoneCode: "+598" },
    { code: "UZ", name: "Uzbekistan", label: "Uzbekistan", phoneCode: "+998" },
    { code: "VA", name: "Vatican City", label: "Vatican City", phoneCode: "+39" },
    { code: "VC", name: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines", phoneCode: "+1" },
    { code: "VE", name: "Venezuela", label: "Venezuela", phoneCode: "+58" },
    { code: "VG", name: "British Virgin Islands", label: "British Virgin Islands", phoneCode: "+1" },
    { code: "VI", name: "U.S. Virgin Islands", label: "U.S. Virgin Islands", phoneCode: "+1" },
    { code: "VN", name: "Vietnam", label: "Vietnam", phoneCode: "+84" },
    { code: "VU", name: "Vanuatu", label: "Vanuatu", phoneCode: "+678" },
    { code: "WF", name: "Wallis and Futuna", label: "Wallis and Futuna", phoneCode: "+681" },
    { code: "WS", name: "Samoa", label: "Samoa", phoneCode: "+685" },
    { code: "YE", name: "Yemen", label: "Yemen", phoneCode: "+967" },
    { code: "YT", name: "Mayotte", label: "Mayotte", phoneCode: "+262" },
    { code: "ZA", name: "South Africa", label: "South Africa", phoneCode: "+27" },
    { code: "ZM", name: "Zambia", label: "Zambia", phoneCode: "+260" },
    { code: "ZW", name: "Zimbabwe", label: "Zimbabwe", phoneCode: "+263" },
];

// Helper functions
export const getCountryByCode = (code: string): Country | undefined => {
    return COUNTRIES.find(country => country.code === code);
};

export const getCountryByName = (name: string): Country | undefined => {
    return COUNTRIES.find(country => country.name === name);
};

export const getPhoneCodeByCountryCode = (code: string): string => {
    const country = getCountryByCode(code);
    return country ? country.phoneCode : "+34"; // Default to Spain
};

export const DEFAULT_COUNTRY_CONFIG = {
    code: "ES",
    name: "Spain",
    label: "Spain",
    phoneCode: "+34",
};