export const RESERVED_SUBDOMAINS = [
    "assets",
    "api",
    "www",
    "admin",
    "dashboard",
    "app",
    "cdn",
] as const;

export const RESERVED_USERNAMES = [
    "admin",
    "administrator",
    "assets",
    "dashboard",
    "tarifa",
    "north",
    "helloworld",
    "api",
    "www",
    "mail",
    "ftp",
    "root",
    "support",
    "help",
    "info",
    "contact",
    "about",
    "login",
    "signup",
    "register",
    "profile",
    "settings",
    "config",
    "system",
    "test",
    "dev",
    "www",
    "api",
    "app",
    "blog",
    "shop",
    "news",
    "dashboard",
    "staging",
    "production",
    "beta",
    "alpha",
    "cdn",
];

export function isUsernameReserved(username: string): boolean {
    return RESERVED_USERNAMES.includes(username.toLowerCase());
}
