import { ENTITY_DATA, type EntityConfig } from "./entities";
import OctagonIcon from "../public/appSvgs/OctagonIcon.jsx";

// users dont need to know about this.
export const HIDDEN_ENTITIES: EntityConfig[] = [
    {
        id: "school_students",
        name: "School Students",
        icon: OctagonIcon,
        color: "text-amber-600",
        bgColor: "bg-amber-400",
        hoverColor: "#fcd34d",
        link: "/ismemberof",
        description: ["Manages the relationship between schools and students."],
        relations: ["school", "student"],
    },
    {
        id: "referral",
        name: "Referrals",
        icon: OctagonIcon,
        color: "text-gray-500",
        bgColor: "bg-gray-300",
        hoverColor: "#e5e7eb",
        link: "/referrals",
        description: ["Tracks referral codes and their associated commissions."],
        relations: ["school", "student_package"],
    },
    {
        id: "booking_student",
        name: "Students Bookings",
        icon: OctagonIcon,
        color: "text-blue-500",
        bgColor: "bg-blue-300",
        hoverColor: "#bbf7d0",
        link: "/bookings",
        description: ["Links students to specific bookings."],
        relations: ["booking", "student"],
    },
    {
        id: "equipment_event",
        name: "Equipment Events",
        icon: OctagonIcon,
        color: "text-sky-500",
        bgColor: "bg-sky-300",
        hoverColor: "#bae6fd",
        link: "/tracking",
        description: ["Assigns specific equipment to scheduled events."],
        relations: ["equipment", "event"],
    },
    {
        id: "equipment_repair",
        name: "Equipment Repairs",
        icon: OctagonIcon,
        color: "text-pink-500",
        bgColor: "bg-pink-300",
        hoverColor: "#fbcfe8",
        link: "/repairs",
        description: ["Logs repair history and costs for equipment."],
        relations: ["equipment"],
    },
    {
        id: "rental",
        name: "Rentals",
        icon: OctagonIcon,
        color: "text-red-500",
        bgColor: "bg-red-300",
        hoverColor: "#fecaca",
        link: "/rentals",
        description: ["Manages direct equipment rentals by students."],
        relations: ["student", "equipment"],
    },
    {
        id: "teacher_equipment",
        name: "Equipment Permissions",
        icon: OctagonIcon,
        color: "text-teal-500",
        bgColor: "bg-teal-300",
        hoverColor: "#99f6e4",
        link: "/permissions",
        description: ["Links teachers to specific equipment."],
        relations: ["teacher", "equipment"],
    },
];

export const TABLE_CONFIG: EntityConfig[] = [...ENTITY_DATA, ...HIDDEN_ENTITIES];
