import type { DateGroup, HomeTransactionEvent } from "./HomePage";

export const MOCK_HOME_GROUPED_DATA: DateGroup[] = [
  {
    date: "2025-01-17",
    events: [
      {
        id: "evt-001",
        date: "2025-01-17T14:00:00Z",
        lessonId: "lesson-001",
        location: "Gym A",
        duration: 120,
        status: "completed",
        teacherUsername: "John",
        packageName: "Beginner Course",
        leaderStudentName: "Alice Johnson",
        categoryEquipment: "snowboard",
        capacityEquipment: 2,
        capacityStudents: 4,
        packageDurationMinutes: 480,
        pricePerStudent: 50,
        commissionType: "fixed",
        commissionValue: 20,
        equipments: [
          {
            id: "eq-001",
            brand: "Burton",
            model: "Custom X",
            size: 160,
          },
        ],
      } as HomeTransactionEvent,
      {
        id: "evt-002",
        date: "2025-01-17T16:30:00Z",
        lessonId: "lesson-002",
        location: "Gym B",
        duration: 90,
        status: "tbc",
        teacherUsername: "Sarah",
        packageName: "Advanced Techniques",
        leaderStudentName: "Bob Wilson",
        categoryEquipment: "ski",
        capacityEquipment: 1,
        capacityStudents: 2,
        packageDurationMinutes: 360,
        pricePerStudent: 75,
        commissionType: "percentage",
        commissionValue: 15,
        equipments: [],
      } as HomeTransactionEvent,
    ],
  },
  {
    date: "2025-01-18",
    events: [
      {
        id: "evt-003",
        date: "2025-01-18T10:00:00Z",
        lessonId: "lesson-003",
        location: "Indoor Arena",
        duration: 150,
        status: "completed",
        teacherUsername: "Maria",
        packageName: "Pro Training",
        leaderStudentName: "Charlie Brown",
        categoryEquipment: "skateboard",
        capacityEquipment: 1,
        capacityStudents: 3,
        packageDurationMinutes: 600,
        pricePerStudent: 100,
        commissionType: "fixed",
        commissionValue: 35,
        equipments: [
          {
            id: "eq-002",
            brand: "Element",
            model: "Pro Deck",
            size: null,
          },
        ],
      } as HomeTransactionEvent,
      {
        id: "evt-004",
        date: "2025-01-18T13:00:00Z",
        lessonId: "lesson-004",
        location: "Park",
        duration: 60,
        status: "planned",
        teacherUsername: "John",
        packageName: "Beginner Course",
        leaderStudentName: "Diana Prince",
        categoryEquipment: "snowboard",
        capacityEquipment: 2,
        capacityStudents: 2,
        packageDurationMinutes: 480,
        pricePerStudent: 50,
        commissionType: "fixed",
        commissionValue: 20,
        equipments: [],
      } as HomeTransactionEvent,
      {
        id: "evt-005",
        date: "2025-01-18T15:30:00Z",
        lessonId: "lesson-005",
        location: "Beach",
        duration: 180,
        status: "completed",
        teacherUsername: "Sarah",
        packageName: "Summer Special",
        leaderStudentName: "Emma Davis",
        categoryEquipment: "ski",
        capacityEquipment: 1,
        capacityStudents: 4,
        packageDurationMinutes: 720,
        pricePerStudent: 60,
        commissionType: "percentage",
        commissionValue: 12,
        equipments: [
          {
            id: "eq-003",
            brand: "Salomon",
            model: "X-Race",
            size: 170,
          },
          {
            id: "eq-004",
            brand: "Atomic",
            model: "Redster",
            size: 165,
          },
        ],
      } as HomeTransactionEvent,
    ],
  },
];

// Example of what HomePage receives
export const MOCK_HOME_PAGE_CONTEXT = {
  schoolName: "Adventure Sports Academy",
  schoolUsername: "adventure-academy",
  currency: "YEN",
  logo: "/school-logo.png",
  stats: {
    duration: 600, // total minutes
    commissions: 25500, // YEN
    profit: 8400, // YEN
    events: 5,
  },
};
